name: validate-bicep

on:
  push:
    branches: [main]

jobs:
  validate-bicep:
    runs-on: ubuntu-latest
    steps:

    # Checkout code
      - name: Checkout
        uses: actions/checkout@v2

    # Log into Azure
      - name: Log into Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

    # Validate Bicep
      - name: Validate
        run: az deployment sub validate -n TestBicep -l eastus2 -f main.bicep -p name=mzv location=eastus2

    # what-if
      - name: what-if
        run: az deployment sub create -n TestBicep -l eastus2 -f main.bicep -p name=mzv location=eastus2 tags={\"env\":\"dev\"}  -w
