name: validate-bicep

on:
  push:
    branches: [main]

jobs:
  validate-bicep:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Validate
        run: az deployment sub validate -n TestBicep -l eastus2 -f main.bicep -p name=mzv location=eastus2
        